### DISCUSSION TITLE
Storage technology generates and consumes carrier by itself

### DISCUSSION THREAD

**Discussion by yiqiaowang-arch** [calliope-project/calliope#524] [Q&A] [answered]
First of all, dear calliope developers, thank you very much for your work! This framework is easy to start with and intuitive, which helps greatly with our project!
## Model Description

I am currently trying to model a ground source heat pump technology, which works with borehole storage. Because boreholes often operates on low temperature (around 15°C), so I defined a special energy carrier called "geothermal storage". 
![image](https://github.com/calliope-project/calliope/assets/28997207/00c9bafa-9152-4d04-86a5-821119b068fd)
When GSHP is heating, it needs to take heat from ground; when it's cooling, it needs to inject (waste) heat back into ground. Since under this definition the conversion_plus technology doesn't work (see #521), I devided GSHP into GSHP_heat and GSHP_cooling, and a storage technology called "geothermal_boreholes", just as it's shown in the graph. The corresponding .yaml setting is below:
<details>
  <summary>code for GSHP and storage</summary>

```yaml
    # GSHP, consumes electricity and consumes geothermal storage to produce heat,
    # or consumes and generate both cooling and geothermal storage
    # with a COP of 4.5
    GSHP_heat:
        essentials:
            name: 'GSHP heating'
            color: '#ffda10'
            carrier_in: electricity
            carrier_in_2: geothermal_storage
            primary_carrier_in: electricity
            parent: conversion_plus
            carrier_out: heat
        constraints:
            energy_eff: 4.5
            energy_cap_min: 10 # kW
            # energy_cap_max: 100000 # kW
            carrier_ratios:
                carrier_in.electricity: 1 # electricity
                carrier_in_2.geothermal_storage: 3.5 # geothermal storage
            lifetime: 30
        costs:
            monetary:
                interest_rate: 0.05
                purchase: 29204 # USD per device
                energy_cap: 750 # USD per kW
                om_annual: 25 # USD per kW, annual maintenance cost based on energy (power) capacity

    GSHP_cooling: # to be defined in group constraints to be strictly coupled with GSHP_heat
        essentials:
            name: 'GSHP cooling'
            color: '#F9CF22'
            carrier_in: electricity
            carrier_out: cooling
            carrier_out_2: geothermal_storage
            primary_carrier_out: cooling
            parent: conversion_plus
        constraints:
            energy_eff: 1
            energy_cap_min: 10 # kW
            # energy_cap_max: 100000 # kW
            carrier_ratios:
                carrier_out.cooling: 4 # cooling
                carrier_out_2.geothermal_storage: 5 # geothermal storage
            lifetime: 30
        costs:
            monetary: # to avoid double counting, only the cost of the heating mode is considered
                interest_rate: 0.05
                purchase: 0 # USD per device
                energy_cap: 0 # USD per kW
                om_annual: 5 # USD per kW, annual maintenance cost based on energy (power) capacity

    # geothermal storage, stores heat, comes with GSHP so no cost
    geothermal_boreholes:
        essentials:
            name: 'Geothermal Boreholes'
            color: '#F9CF22'
            parent: storage
            carrier: geothermal_storage
        constraints:
            energy_eff: 0.9 # one way efficiency
            # force_asynchronous_prod_con: true # charge and discharge are not simultaneous
            lifetime: 30
            storage_cap_max: 100000 # kWh
            energy_cap_max: 100000 # kW
            storage_loss: 0.001 # 0.1% loss per hour
            storage_initial: 0.9 # initial storage level, building needs some storage to survive the winter
        costs:
            monetary:
                interest_rate: 0.05
                om_annual_investment_fraction: 0 # fraction of purchase cost
                storage_cap: 0 # already included in the cost of GSHP
```
</details>
Because I only found cost function for GSHP combined with boreholes, so I set only GSHP_heat with purchase and capacity cost, while GSHP_cooling and boreholes are considered to be free, and I keep the `cyclic_storage` to be `true`. I would assume, that if GSHP_heat is not chosen, then to reach the heat balance of boreholes, GSHP_cooling should also not be chosen, as at the end of the year, the storage state has to be true.

## Issues when optimizing
During the optimization, **I set one building's GSHP purchase and cap cost to be zero**, because it already has GSHP installed and doesn't need to buy it again. Basically, I'm trying to promote this building to use GSHP. However, with the presense of a more expensive ASHP (the building needs to buy it), optimizer never chooses GSHP_heat, but chooses GSHP_cooling. Only when I disabled ASHP, optimizer started to choose GSHP_heat. 
Setup of my ASHP:
<details>
  <summary>ASHP</summary>
```yaml
    # ASHP, consumes electricity to produce heat, with a COP of 2.4
    ASHP:
        essentials:
            name: 'ASHP SH/SC'
            color: '#676767'
            carrier_in: electricity
            carrier_out: [heat, cooling]
            primary_carrier_out: heat
            parent: conversion_plus
        constraints:
            energy_eff: 1
            energy_cap_min: 1 # kW
            carrier_ratios:
                carrier_out: {heat: 2.4, cooling: 3}
            lifetime: 25
        costs:
            monetary:
                interest_rate: 0.05
                purchase: 19128 # USD per device
                energy_cap: 167 # USD per kW
                om_annual: 11 # USD per kW, annual maintenance cost based on energy (power) capacity
```
</details>
Then I looked into the operation of GSHP and boreholes, finding out that borehole automatically produces/consumes much more than what GSHP actually consumes/produces. Here's what the hourly operational profile of all technologies regarding geothermal_storage carrier look like:

![image](https://github.com/calliope-project/calliope/assets/28997207/e9c30b7e-0744-47e8-9e38-b49941bd4784)

As shown in the graph, the outflow and inflow of geothermal borehles (red and blue curves) are much higher than what was produced by GSHP_cooling (yellow) and GSHP_heat (green), showing that the storage is producing and consuming energy on itself. 

Also, even though GSHP_heat is used, it doesn't work in the winter. In the winter the heating demand is satisfied by wood boilers. I don't understand where does the extra heat produced by GSHP_heat goes.

![image](https://github.com/calliope-project/calliope/assets/28997207/c8ccaac8-6b91-4a3d-8a54-73e67f771ea6)

## Possible solutions
A few possible issues and corresponding solutions are yet to try out:

1. my borehole naturally loses heat (I set storage_loss to be 0.001), and this causes a natural favor of having a GSHP_cooling (in my case it's free) that provides it with waste heat, so that in the end it can satisfy cyclic_storage. Solution would be to give GSHP_cooling a fair price;
2. I assume that the charge and discharge of boreholes are with no cost, maybe that's why it operates freely. Solution could be that I add an operation cost for charging/discharging of boreholes, and this would be more realistic because it requires some electricity to pump the water. 
3. I still have no idea where the extra heating in summer goes, maybe I will look into lp file to find out.
4. Regarding the issue that ASHP is favored with much higher CAPEX and lower COP (even when electricity is crazily expensive), maybe if I solve the previous two issues, this will also be solved.

I will post updates if I have new findings.
