### ISSUE TITLE
Custom constraints

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#100]
In 0.6.0 we have (temporarily?) removed the ability to introduce custom constraints via the YAML format*. 

To bring it back in, ideally a user could have one Python script which introduces any new sets, parameters, decision variables, and constraints. If we provide a template for this, it would ensure that a user includes all the necessary information to produce the desired results.

## Steps to introduce the functionality

- [ ] Get list of all data required to build a brand new constraint
- [ ] Build a custom constraint template and test with a new constraint

* A user familiar with Pyomo can currently add a custom constraint after building the backend model (``model.run(build_only=True)``) by accessing the Pyomo ConcreteModel directly via ``model._backend_model``.

**Comment by sjpfenninger** [comment]
Always sets for each `tech` and `tech_group` to allow you to easily attach per-tech custom constraints via those sets?

**Comment by timtroendle** [comment]
Here's a work-in-progress suggestion of how custom constraints could look like in the yaml file. The idea is that next to the user-friendly Calliope structure, one can manually add ´Sets´, `Parameters`, `Variables`, and `Constraints`.

The constraints defined below are the group constraints in Calliope 0.6.5. It requires #322 to be solved first.

``` yaml
custom_constraints:
    sets:
        wind_techs:
            elements:
                - onshore_wind
                - offshore_wind
            within: techs
        ac_transmission:
            elements:
                - ac_transmission
            within: techs
        nordic_countries:
            elements:
                - FIN
                - CHE
                - NOR
            within: locs
        tims_favorite_timesteps:
            elements:
                - "2016-04-01 04:00"
                - "2016-06-16 08:00"
            within: timesteps
        monetary_cost:
            elements:
                - monetary
            within: costs
    parameters:
        carrier_prod_share: 0.25
        net_import_share: 0.7
        energy_cap_share: 0.2
        energy_cap: 200
        cost_cap: 1e6
        cost_var_cap: 1e4
        cost_investment_cap: 1e3
        resource_area_cap: 100
    # TODO add variables
    constraints:
        net_import_share:
            foreach: [nordic_locs, carriers]
            eq: net_import_sum <= net_import_share * demand_sum
            components:
                net_import_sum:
                    sum: carrier_prod + carrier_con
                    over: [ac_transmission, timesteps]
                demand_sum:
                    sum: carrier_con
                    over: [demand, timesteps]

        carrier_prod_share:
            eq: energy_sum_wind <= carrier_prod_share * total_energy_sum
            foreach: [nordic_locs, carriers]
            components:
                energy_sum_wind:
                    sum: carrier_prod
                    over: [wind_techs, timesteps]
                total_energy_sum:
                    sum: carrier_prod
                    over: [supply_techs, timesteps]
            # TODO: allow for conditional statements

        energy_cap_share:
            eq: energy_cap_sum_wind <= energy_cap_share * energy_cap_sum_all
            foreach: [locs, electricity]
            components:
                energy_cap_sum_wind:
                    sum: energy_cap
                    over: [wind_techs]
                energy_cap_sum_all:
                    sum: energy_cap
                    over: [techs_supply]

        energy_cap:
            eq: energy_cap_sum_wind <= energy_cap
            foreach: [locs, electricity]
            components:
                energy_cap_sum_wind:
                    sum: energy_cap
                    over: [wind_techs]

        carrier_prod_share_per_timestep:
            eq: energy_sum_wind <= carrier_prod_share * total_energy_sum
            foreach: [nordic_locs, carriers, tims_favorite_timesteps]
            components:
                energy_sum_wind:
                    sum: carrier_prod
                    over: [wind_techs]
                total_energy_sum:
                    sum: carrier_prod
                    over: [supply_techs]

        demand_share:
            foreach: [locs, carriers]
            eq: net_import_sum <= demand_share * -1 * demand_sum
            components:
                net_import_sum:
                    sum: carrier_prod
                    over: [wind_techs, timesteps]
                demand_sum:
                    sum: carrier_con
                    over: [demand, timesteps]

        resource_area:
            foreach: []
            eq: resource_area_sum <= resource_area_cap
            components:
                resource_area_sum:
                    sum: resource_area
                    over: [wind_techs, nordic_countries]

        cost_cap:
            foreach: [monetary_cost]
            eq: cost_sum <= cost_cap
            components:
                cost_sum:
                    sum: cost
                    over: [locs, techs, timesteps]

        cost_var_cap:
            foreach: [monetary_cost]
            eq: cost_sum <= cost_cap
            components:
                cost_sum:
                    sum: cost_var
                    over: [locs, techs, timesteps]

        cost_investment_cap:
            foreach: [monetary_cost]
            eq: cost_sum <= cost_cap
            components:
                cost_sum:
                    sum: cost_investment
                    over: [locs, techs]
    #TODO needs a variable
    # c1: carrier_prod[hp, t] / resource[demand_tech, t] == decision_var[hp]
    # c2: decision_var[hp] + decision_var[boiler] = 0.8
```

**Comment by brynpickering** [comment]
Some thoughts on this. We can leverage the update to how constraint sets are built in #346 to make it easier to define constraints in YAML. In `config/subsets.yaml`, each named constraint has the dimensions over which the constraint is built and a `where` "mask" to tell it whether to consider an indexed component or not. E.g.:

```yaml
carrier_consumption_max:
        foreach: [nodes, techs, carriers, timesteps]
        where: [carrier, and, [inheritance(transmission), or, inheritance(demand), or, inheritance(storage)], and, [not cap_method='integer', or, inheritance(demand)], and, allowed_carrier_con=True]
        subset:
            carrier_tiers: [in]
```

This means that the internal constraints should never need to check if the indexed component is valid, since it is pre-filtered when generating the constraint set. 

For the above, the YAML constraint should then be able to look like this, without any additional 'components':

```yaml
carrier_consumption_max:
    eq: carrier_con >= -1 * energy_cap * timestep_resolution
```
