### ISSUE TITLE
Just `interest_rate` in cost leads to error

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#113]
## Problem description

After calculating depreciation rate, the parameter `interest_rate` is deleted from a technology's configuration. So, if it only defined `interest_rate` it now has an empty cost dictionary. 

This causes an error at: ``/calliope/core/preprocess/model_data.py, line 236``

## Steps to reproduce the problem

Describe a technology as follows:

```yaml
    tech_1:
        essentials:
            color: "#2e382f"
            parent: supply
            name: some_supply_tech
            carrier: a_fuel
        constraints:
            lifetime: 25
            energy_cap_max: .inf
        costs:
            monetary:
                interest_rate: 0.1
```
And it will fail. 

## Calliope version

0.6.2-dev (6348b84)
