### ISSUE TITLE
Graceful failure of empty cost classes

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#190]
## Problem description

If you define a cost class without any costs, it will fail on expectation that the value of that cost class is a dictionary, instead it will find nothing (i.e. `None`).

E.g.

```yaml
techs:
    this_tech:
        essentials:
            carrier: foo
            parent: supply
            name: bar
        constraints:
            energy_cap_max: inf
            resource: inf
        costs:
            monetary:
                om_prod: 5  # this cost class will not cause an exception
            carbon:
                # this empty cost class will cause an exception to be raised
```

We could do with either ignoring `carbon` or making it obvious what the error is... 

## Calliope version

0.6.3
