### ISSUE TITLE
Fail or warn with unknown tech parameters

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#207]
## Problem description

Calliope isn't fool-proof enough for a fool like me. When you forget to properly indent your YAML file, things can go wrong without notice. Consider this tech with high costs:

```yaml
my_tech:
        essentials:
            name: 'My tech'
            parent: storage
            carrier: electricity
        constraints:
            energy_cap_max: inf
            storage_cap_max: inf
        costs:
        monetary: # oh no!
            energy_cap: 112345
```

But because the indentation is wrong, this tech is actually cost free.

Currently, this goes unnoticed. The user is not warned, the execution does not stop, and there are no costs considered. 

## Calliope version

0.6.4.dev
