### ISSUE TITLE
FutureWarning for cost class default value is always issued

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#222]
## Problem description

I always see the new FutureWarning 

```
FutureWarning:

There will be no default cost class for the objective function in v0.7.0 (currently "monetary" with a weight of 1). Explicitly specify the cost class(es) you would like to use under `run.objective_options.cost_class`. E.g. `{"monetary": 1}` to replicate the current default.
```

I _do_ have the cost class specified explicitely though:

```yaml
objective_options: {
        'cost_class': {'monetary': 1},
        'sense': 'minimize'
    }
```

I guess the problematic line is the one in `model.py` L 315:

```Python
if AttrDict.from_yaml_string(self._model_data.attrs['run_config']).objective_options.cost_class == {'monetary': 1}:
```

## Calliope version

0.6.4.dev

_What exact version of Calliope are you using?_
