### ISSUE TITLE
energy_cap_per_storage_cap enforced for `supply_plus`

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#236]
## Problem description

`supply_plus` technologies are forced to have an `energy_cap_per_storage_cap` constraint. That seems wrong to me. It's furthermore inconsistent with `storage` techs. See minimal example below.

The error message is:
```
Error in print_warnings_and_raise_errors:
Errors during model processing:
 * `hydro_reservoir` at `DEU` fails to define energy_cap_per_storage_cap, but is using storage
```

This seems to be a regression. The commit which introduced it is: 0de3d85f6f1f62214bd0fb8e17ec48e0f7b3b01b.

## Steps to reproduce the problem

Minimal model below. Without the last line, Calliope throws an error.

```yaml
model:
    name: test
    timeseries_data_path: '.'
    subset_time: '2016-01-01'

run:
    mode: plan
    solver: gurobi
    solver_io: python

techs:
    supply_bumm:
        essentials:
            name: Cheap supply tech
            carrier: electricity
            parent: supply
        constraints:
            lifetime: 25
            energy_cap_max: .inf
        costs:
            monetary:
                interest_rate: 0.1
                energy_cap: 10
    electricity_demand:
        essentials:
            name: Electricity demand
            carrier: electricity
            parent: demand
        constraints:
            resource: file=electricity-demand.csv
    hydro_reservoir:
        essentials:
            name: Hydro electricity with a reservoir.
            parent: supply_plus
            carrier: electricity
        constraints:
            resource: inf
            energy_cap_equals: 5
            storage_cap_equals: 10
    pumped_hydro:
        essentials:
            name: 'Pumped hydro power storage'
            parent: storage
            carrier: electricity
        constraints:
            energy_cap_equals: 5
            storage_cap_equals: 10
            energy_eff: 0.9

locations:
    DEU:
        techs:
            supply_bumm:
            electricity_demand:
            pumped_hydro:
            hydro_reservoir:
                constraints:
                    energy_cap_per_storage_cap_equals: 0.5 # breaks without this line
```

## Calliope version

0.6.4.dev
