### ISSUE TITLE
Suspicious Pyomo warning for storage_capacity_constraint and energy_capacity_constraint

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#237]
## Problem description

While investigating #236, I've encountered a nasty Pyomo warning which wasn't there before.

The warning message is:
```
WARNING: Implicitly replacing the Component attribute
    storage_capacity_constraint (type=<class
    'pyomo.core.base.constraint.IndexedConstraint'>) on block unknown with a
    new Component (type=<class
    'pyomo.core.base.constraint.IndexedConstraint'>). This is usually
    indicative of a modelling error. To avoid this warning, use
    block.del_component() and block.add_component().
WARNING: Implicitly replacing the Component attribute
    energy_capacity_constraint (type=<class
    'pyomo.core.base.constraint.IndexedConstraint'>) on block unknown with a
    new Component (type=<class
    'pyomo.core.base.constraint.IndexedConstraint'>). This is usually
    indicative of a modelling error. To avoid this warning, use
    block.del_component() and block.add_component().
```

This is a regression which was introduced in e8792ddbbc714db82d9f6cbeb6adb97becc0660d.

## Steps to reproduce the problem

Minimal model below. Without the pumped hydro, there is only the energy_cap warning. With it, there is as well the storage_cap warning.

```yaml
model:
    name: test
    timeseries_data_path: '.'
    subset_time: '2016-01-01'

run:
    mode: plan
    solver: glpk

techs:
    supply_bumm:
        essentials:
            name: Cheap supply tech
            carrier: electricity
            parent: supply
        constraints:
            lifetime: 25
            energy_cap_max: .inf
        costs:
            monetary:
                interest_rate: 0.1
                energy_cap: 10
    electricity_demand:
        essentials:
            name: Electricity demand
            carrier: electricity
            parent: demand
        constraints:
            resource: file=electricity-demand.csv
    pumped_hydro:
        essentials:
            name: 'Pumped hydro power storage'
            parent: storage
            carrier: electricity
        constraints:
            energy_cap_equals: 5
            storage_cap_equals: 10
            energy_eff: 0.9

locations:
    DEU:
        techs:
            supply_bumm:
            electricity_demand:
            pumped_hydro:
```

## Calliope version

0.6.4.dev
