### ISSUE TITLE
Permit per_timestep group shares to be planning decisions

### ISSUE THREAD

**Issue by sjpfenninger** [calliope-project/calliope#239]
## Problem description

It should be possible to make the fractions of each technology in a group_share constraint should a decision variable, such that in each hour, the shares must add up to a given fraction, but the shares themselves are time-independent decision variables.

## Possible example configuration

```
group_constraints:
    model_decides_shares:
        locs: []  # optional
        techs: []  # only makes sense to set if share for a carrier is <1.0  -- warn otherwise?
        demand_share_per_timestep_equals_planning_decision:
            carrier: 1.0  # share of the carrier that the model gets to decide on
```
