### ISSUE TITLE
Do not heat up the environment

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#268]
## Problem description

There is an implicit sector coupling feature in Calliope which makes Calliope heat up transmission links whenever too much energy is available. See the minimal model below.

In my case, wasting electricity on transmission lines seems to be an alternative to curtailing renewables. Wasting electricity on transmission lines has three disadvantages I would say:

1. It's much more difficult to say how much renewable energy has been "curtailed".
2. It's more difficult to say how much energy has been "traded".
3. I assume it makes the problem much harder to solve, because it doubles the amount of independent variables (``carrier_prod[transmission]``) and it creates plateaus on the feasible set: it really makes no or almost no difference where you burn the electricity.

It astonished me to see how extensive this effect is: quite contrary to my intuition, using the transmission link in both directions in parallel seems to be the normal case, not the exception. This may or may not be related to the fact that I am not using crossover.

It would be great if there was an option to switch off this behaviour.

## Steps to reproduce the problem

Minimal model below. The idea here is that demand is often = 10, but the supply must always be 15. Calliope burns the surplus electricity on huge transmission lines.

```yaml
model:
    name: Transmission test
    timeseries_data_path: '.'

run:
    mode: plan
    solver: cbc
    objective_options.cost_class: {monetary: 1}

techs:
    inflexible_supply:
        essentials:
            name: Inflexible electricity supply
            parent: supply
            carrier: electricity
        constraints:
            lifetime: 25
            energy_cap_equals: 15
            energy_cap_min_use: 1
        costs:
            monetary:
                interest_rate: 0.1
                energy_cap: 20
    demand_elec:
        essentials:
            name: Electricity demand
            carrier: electricity
            parent: demand
        constraints:
            resource: file=demand.csv

    hot_transmission:
        essentials:
            name: 'Power transmission'
            parent: transmission
            carrier: electricity
        constraints:
            energy_cap_max: inf
            energy_eff: 0.95
            lifetime: 25
        costs:
            monetary:
                interest_rate: 0.1
                energy_cap_per_distance: 0.0005

locations:
    0: # Austria
        coordinates: {lat: 47.58707180296529, lon: 14.140267800609571}
        techs:
            demand_elec:
            inflexible_supply:
    1: # Belgium
        coordinates: {lat: 50.64103513383204, lon: 4.661121087007843}
        techs:
            demand_elec:
            inflexible_supply:

links:
    0,1:
        techs:
            hot_transmission:
```

## Calliope version

0.6.4
