### ISSUE TITLE
Export_cap cannot exceed energy_cap

### ISSUE THREAD

**Issue by alicestamp** [calliope-project/calliope#315]
It would be great to be able to model batteries that can discharge more quickly than they can charge.

Currently this is limited by the fact that carrier_prod[t] <= energy_cap. Essentially want to be able to toggle off the constraint if export_cap > energy_cap.

A workaround is to use a conversion tech to create a proxy energy_cap for the storage tech to limit carrier_con, then set the actual energy_cap of the storage tech as the export_cap value.

**Comment by sjpfenninger** [comment]
The aim is that this will be resolvable via a custom constraint (#100).

**Comment by brynpickering** [comment]
This can now be readily dealt with in the new custom math syntax:

```yaml
constraints:
  limit_export_cap:
    description: "Fix the relationship between between export capacity and outflow capacity."
    foreach: [nodes, techs, carriers]
    where: flow_export
    equations:
      - expression: export_max <= flow_out_cap
```

^ I haven't tested this, but should do the trick.
