### ISSUE TITLE
Explicit links

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#324]
## Problem description

The current way of modelling links has some issues:

1. There are loads of link technologies, which makes analysing results complicated and which often requires special case treatment (for example in halving link capacities).
2. Building a network model of Calliope results is rather difficult.

Instead, it would probably good to model links explicitly ([potential example in the Pyomo doc](https://pyomo.readthedocs.io/en/stable/pyomo_modeling_components/Sets.html#sparse-index-sets)). 

## Calliope version

0.6.5

**Comment by brynpickering** [comment]
Linking with #326 and #362, we could use lists of dicts to define links, e.g.:

from:
```
links:
    X1,X2:
        techs:
            power_lines:
                distance: 10
```
to: 
```
links:
    - id: my_link # (this *could* be optional)
      from: X1
      to: X2
      link_techs:
        - id: power_lines
          distance: 10
```
Since transmission technologies are their own beast, having them defined under a top-level key `link_techs` might not be a bad idea. I think @sjpfenninger has some more he can add on this from an offline discussion.
