### ISSUE TITLE
energy_cap_max and storage_cap_max are not handled correct on intervals of 15 minutes

### ISSUE THREAD

**Issue by lblabr** [calliope-project/calliope#342]
## Problem description
the storage tech is not handled correct on intervals with 15 minutes

## Steps to reproduce the problem

add time series with 15 minutes interval and configure stoarge tech according the physical parameters 

```
    battery:
        essentials:
            name: 'Battery Storage'
            color: '#3B61E3'
            parent: storage
            carrier: electricity
        constraints:
            energy_cap_max: 3680  # kW
            storage_cap_max: 9800
            energy_eff: 0.95  # 0.95 * 0.95 = 0.9025 round trip efficiency
            storage_loss: 0.03  # No loss over time assumed
            lifetime: 25
#            force_asynchronous_prod_con: false
        costs:
            monetary:
                interest_rate: 0.10

```
the battery gets charged with 1/4 of the capacity

![15min_01](https://user-images.githubusercontent.com/5998943/100157715-4f522180-2eab-11eb-9739-774acb4feb33.PNG)

should be:

![15min_02](https://user-images.githubusercontent.com/5998943/100157841-8c1e1880-2eab-11eb-95f4-732fa1933a87.PNG)

edit 2020-11-25

in addition to the wrong interpretation of the constraints, the result export is not correct / timeseries plot (html) seems to work...

![15min_04](https://user-images.githubusercontent.com/5998943/100194007-35d5c780-2ef5-11eb-8660-5a38c6cc2f84.PNG)
![15min_03](https://user-images.githubusercontent.com/5998943/100194010-366e5e00-2ef5-11eb-8514-8a651abb54dc.PNG)

## Calliope version
0.6.6-post 1
