### ISSUE TITLE
Enabling location_groups

### ISSUE THREAD

**Issue by ramaroesilva** [calliope-project/calliope#351]
**Problem description**
Calliope only allows group configurations for techs (with tech_groups), but extending this to locations would also be nice.

E.g. it would simplify writing the locations YAML for a case-study with several houses, each with the same load and PV tech.

**Comment by brynpickering** [comment]
You can already do this, e.g.:

```yaml
locations:
     location1, location2, location3:
         techs: 
         ...
```

Is equivalent to:

```yaml
locations:
     location1:
         techs: ...
     location2:
         techs: ...
     location3:
         techs: ...
```

Where the content of `techs` will be identical in each location. You can even do this for most of your techs and still define specific parameters for certain locations:

```yaml
locations:
     location1, location2, location3:
         techs:
             pv: 
     location1:
         techs:
             wind.energy_cap_max: 1
```

See the [national scale example model tutorial](https://calliope.readthedocs.io/en/stable/user/tutorials_01_national.html) for an example of its application
