### ISSUE TITLE
Better handle carrier definitions in YAML

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#377]
## Problem description

Moving the carrier definition component of #362 here.

We currently have a relatively complex way to handle defining carriers. Actually, it isn't complicated until we define "conversion_plus" technologies. All the complex ways of doing it are given [in the docs](https://calliope.readthedocs.io/en/v0.6.8/user/advanced_constraints.html#the-conversion-plus-tech). Ideally, we can structure this in a more coherent way, along the lines of using lists of dictionaries. Let's take a complex example and consider it from a range of angles:

```yaml
cchp:
    essentials:
        name: Combined cooling, heat and power
        carrier_in: [fossil_gas, synthetic_gas]
        carrier_out: electricity
        carrier_out_2: [heat, cooling]
        primary_carrier_out: electricity
        primary_carrier_in: fossil_gas

    constraints:
        energy_eff: 0.45
        energy_cap_max: 100
        carrier_ratios.carrier_out_2: {heat: 0.8, cooling: 0.5}
```

a.
```yaml
id: cchp
name: Combined cooling, heat and power
carriers:
    - tier: in
      carrier: [fossil_gas, synthetic_gas]
      ratios: [1, 1]
      primary: fossil_gas
    - tier: out
      carrier: electricity
      primary: electricity
    - tier: out_2
      carrier: [heat, cooling]
      ratios: [0.8, 0.5] 
energy_eff: 0.45
energy_cap_max: 100
```
b. 
```yaml
id: cchp
name: Combined cooling, heat and power
carriers:
    - tier: in
      carrier: fossil_gas
      primary: true
    - tier: in
      carrier: synthetic_gas
    - tier: out
      carrier: electricity
      primary: true
    - tier: out_2
      carrier: heat
      ratio: 0.8
    - tier: out_2
      carrier: cooling
      ratio: 0.5
energy_eff: 0.45
energy_cap_max: 100
```
c.
```yaml
id: cchp
name: Combined cooling, heat and power
carriers:
    in:
      - carrier: fossil_gas
        primary: true
      - carrier: synthetic_gas
    out:
      - carrier: electricity
        primary: true
    out_2:
      - carrier: heat
        ratio: 0.8
      - carrier: cooling
        ratio: 0.5
energy_eff: 0.45
energy_cap_max: 100
```

d.
```yaml
id: cchp
name: Combined cooling, heat and power
carriers:
    in:
      - tier: 1
        carrier: fossil_gas
        primary: true
      - tier: 1
        carrier: synthetic_gas
    out:
      - tier: 1
        carrier: electricity
        primary: true
      - tier: 2
        carrier: heat
        ratio: 0.8
      - tier: 2
        carrier: cooling
        ratio: 0.5
energy_eff: 0.45
energy_cap_max: 100
```

Since the 'carrier tiers' (in, out, in_2, out_2, etc.) are going to be dimensions of the dataset, `c`/`d` might work best (i.e. explicit keys for the carrier tiers). However, to work with loading data from tabular form (#92), limited nesting would be ideal. 

Irrespective of how we approach the problem, `ratios` are still somewhat difficult to wrap one's head around. They link tiers > 1 to tier == 1 (e.g. `carrier_prod[heat] / carrier_prod[electricity] == 0.8`), but this isn't clear from their definition.
