### ISSUE TITLE
Remove `equals` and `scale` bounds

### ISSUE THREAD

**Issue by sjpfenninger** [calliope-project/calliope#422]
Right now, variables can define `equals` and `scale`:

```
variables:
  energy_cap:
    foreach: [nodes, techs]
    where: "NOT run.mode=operate"
    bounds:
      min: energy_cap_min
      max: energy_cap_max
      equals: energy_cap_equals
      scale: energy_cap_scale
```

We want to remove the functionality for both of these.

`equals` can be handled by setting `min` and `max` to the same value, `scale` is rarely needed and can be handled separately (e.g. with an additional parameter) where it is needed.

Pyomo recommends the approach of setting min and max to the same value to fix variables:

https://pyomo.readthedocs.io/en/stable/working_models.html#fixing-variables-and-re-solving
