### ISSUE TITLE
conversion_plus techs producing energy above e_cap

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#50]
If you set up a problem as:

```yaml
reversible_heat_pump:
    name: 'Reversible Heat Pump'
    parent: conversion_plus
    primary_carrier: power #
    carrier_in: gas
    carrier_out:
        power: 1
        heat: 1
    constraints:
        e_cap.max: 1300 # cannot produce more than 1300kWh per hour
```

Then `e_cap.max` applies to `power` (the primary carrier), but not to `heat`, allowing `heat` to be produced above the value set by `e_cap.max`. Requires editing `c_prod_max_rule` and `c_prod_min_rule` to consider the sum of all carriers in `carrier_out` as being limited by `e_cap`
