### ISSUE TITLE
Problems modelling PV/T panels

### ISSUE THREAD

**Issue by yiqiaowang-arch** [calliope-project/calliope#521]
## Problem description

PV/T panels generate heat and electricity at the same time, but their yield is not correlated via a constant. For this, I prepared two dataframes, one for electricity generation, another one for heat generation. 
I need to use supply_plus as parent of my PV/T panels, because the total area is limited and PV/T has to compete with other solar technologies (PV, Solar Collector), and conversion_plus doesn't allow the constraint of `resource_unit: energy_per_area`. 
However, with supply_plus, I cannot define a different heat yield, creating an inaccuracy of the model.

## Steps to reproduce the problem
Here's my configuration of PV/T panel in yaml, where I set the input resource to be the same as electricity yield (`supply_PVT_e`) and set the electricity output to 1, so it always gives me the correct electricity yield; for heat output, I calculated the relative ratio of heat comparing to electricity. 
For example, if at 12:00 my PVT generates 1kWh electricity and 4kWh heat, and at 13:00 1.5kWh electricity and 5kWh heat, I will need a time-series output ratio for heat, which is 4 at 12:00 and 3.33 at 13:00, and my `supply_PVT_h` dataframe contains this ratio.

```yaml
    PVT:
        essentials:
            name: 'PVT'
            color: '#E37A72'
            parent: supply_plus
            carrier_out: electricity
            carrier_out_2: heat
            primary_carrier_out: electricity
        constraints:
            export_carrier: electricity
            resource: df=supply_PVT_e
            resource_unit: energy_per_area
            carrier_ratios:
                carrier_out:
                    electricity: 1
                carrier_out_2:
                    heat: df=supply_PVT_h
            energy_eff: 1
            resource_area_per_energy_cap: 10 # 10m2 per kWp electricity
            lifetime: 15
        costs:
            monetary:
                interest_rate: 0.05
                energy_cap: 2600 # CHF per kW
                om_annual_investment_fraction: 0.01 # fraction of purchase cost
                export: -0.05 # CHF per kWh, feed-in tariff
```
And this is my calliope error traceback:
```
---------------------------------------------------------------------------
ModelError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 model = calliope.Model(building_specific_config, timeseries_dataframes = dict_timeseries_df)

File ~\OneDrive\Experiments\re_optimization\venv\lib\site-packages\calliope\core\model.py:81, in Model.__init__(self, config, model_data, *args, **kwargs)
     79     self._init_from_model_run(model_run, debug_data)
     80 elif isinstance(config, dict):
---> 81     model_run, debug_data = model_run_from_dict(config, *args, **kwargs)
     82     self._init_from_model_run(model_run, debug_data)
     83 elif model_data is not None and config is None:

File ~\OneDrive\Experiments\re_optimization\venv\lib\site-packages\calliope\preprocess\model_run.py:113, in model_run_from_dict(config_dict, timeseries_dataframes, scenario, override_dict)
    107 config.config_path = None
    109 config_with_overrides, debug_comments, overrides, scenario = apply_overrides(
    110     config, scenario=scenario, override_dict=override_dict
    111 )
--> 113 return generate_model_run(
    114     config_with_overrides,
    115     timeseries_dataframes,
    116     debug_comments,
    117     overrides,
    118     scenario,
    119 )

File ~\OneDrive\Experiments\re_optimization\venv\lib\site-packages\calliope\preprocess\model_run.py:742, in generate_model_run(config, timeseries_dataframes, debug_comments, applied_overrides, scenario)
    740 final_check_comments, warning_messages, errors = checks.check_final(model_run)
    741 debug_comments.union(final_check_comments)
--> 742 exceptions.print_warnings_and_raise_errors(warnings=warning_messages, errors=errors)
    744 # 9) Build a debug data dict with comments and the original configs
    745 debug_data = AttrDict(
    746     {
    747         "comments": debug_comments,
    748         "config_initial": config,
    749     }
    750 )

File ~\OneDrive\Experiments\re_optimization\venv\lib\site-packages\calliope\exceptions.py:80, in print_warnings_and_raise_errors(warnings, errors)
     74     warn(
     75         "Possible issues found during model processing:\n"
     76         + textwrap.indent("\n".join(sorted(list(set(warnings)))), " * ")
     77     )
     79 if errors:
---> 80     raise ModelError(
     81         "Errors during model processing:\n"
     82         + textwrap.indent("\n".join(sorted(list(set(errors)))), " * ")
     83     )
     85 return None

ModelError: Errors during model processing:
 * `PVT` at `B162298` defines non-allowed constraint `carrier_ratios`
```

## Calliope version

0.6.10
