### ISSUE TITLE
Documentation not clear: time series data import from pandas DataFrame

### ISSUE THREAD

**Issue by yiqiaowang-arch** [calliope-project/calliope#522]
When adding time series data while running calliope in python, I found the documentation for this is really fragmented and there's little description on how I can pass dataframe into the model. I have figured it out myself; but I would suggest that a clearer tutorial is favored for other users.

What I did for the preparation:

1. for every time-series data entry in the yaml file, I need a specified name for that data;
2. in model configuration, I need **a pair of empty large bracket** as a placeholder of my future input from python:
```yaml
model:
    name: 'building in plot 8'
    calliope_version: 0.6.10
    timeseries_data: {} # I think this is the most critical part, as it's not mentioned anywhere in the documentation.
    subset_time: ['2050-01-01', '2050-01-02']
```
3. In python, every time series data entry needs a separate dataframe, which should have the column name identical with the location name;
4. Then I need to construct a dict, with keys equals to the previous specified name, and values as corresponding dataframe, 
5. finally, when setting up model, I need to pass `timeseries_dataframes=dict_of_dfs`:
```python
model = calliope.Model(building_specific_config, timeseries_dataframes=dict_timeseries_df)
```

Issues about documentation:

- In Building a model - time series data: it only mentioned how to pass dict into model, but no information about how to setup model configuration that supports passing dataframe into it;
- In Running a model - Running interactively with Python: It also did not mention how to read dataframe from python, although this chapter was recommended when reading "Building a model - time series data";
- In Tutorials: this chapter is recommended when reading "Running a model - Running interactively with Python", but it still has no info about time series data from dataframe;
- In Configuration and defaults - Model configuration: timeseries_data is mentioned to replace timeseries_data_path, but I cannot find examples on how to set value to this key.
