### ISSUE TITLE
Ramping constraint for conversion and conversion_plus

### ISSUE THREAD

**Issue by arnaud-leroy** [calliope-project/calliope#55]
Hello,

After testing the ramping constraint on **conversion** technology by adding:
- in model.yaml : constraints:     - constraints.optional.ramping_rate
- in tech.yaml : constraints:         e_ramping: 0.1

I observed the error:
ERROR: Rule failed when generating expression for constraint c_ramping_up with index ('boiler', 'L1', Timestamp('2005-01-01 01:00:00')):
	OptionNotSetError: Can not get parent for `conversion` and no default defined (boiler.carrier).

The same error appears for **conversion_plus** technology but not for **supply** technology

Thanks!

**Comment by brynpickering** [comment]
Since version 0.5.0 of Calliope, there's been some backward incompatible changes to technology definitions, once of which involved changing from having `carrier` and `source_carrier` to having `carrier_in` and `carrier_out`. This wasn't updated in the optional constraints, but I've now dealt with it in commit 0a0c1c0.

You'll need to wait until version 0.5.3 is released to see these changes, or get yourself a local version of Calliope 0.5.2dev, by following the instructions here: https://calliope.readthedocs.io/en/stable/user/develop.html#installing-a-development-version

**Comment by arnaud-leroy** [comment]
Thanks Bryn,

I downloaded the development version. The ramping seemed to work at a first glance but I tried putting a e_ramping: 0 to a conversion technology. 

```
    test_ramp:
        name: 'Conversion tech'
        parent: conversion
        export: true
        carrier_in: gas
        carrier_out: heat
        constraints:
            e_cap.max: 30
            e_eff: 0.6399
            e_ramping: 0
            e_cap_min_use: 0.3
        costs:
            monetary:
                e_cap: 120
                om_var: 2.7

```

I was expecting a constant output. But the output value change once per day:
![image](https://user-images.githubusercontent.com/29625919/28203966-40e00192-687c-11e7-8b50-87775b619533.png)
