### ISSUE TITLE
Different behaviour between conversion and conversion_plus

### ISSUE THREAD

**Issue by arnaud-leroy** [calliope-project/calliope#58]
I don't know if it is a bug or if I misunderstand it but I have some troubles to understand some difference between the behavior of conversion and conversion_plus technologies, especially regarding the secondary carrier and the export option. The model is a bit fictional but here are the code I used for a conversion technology and if you remove the # and change the "conversion" by "conversion_plus", you will have a conversion_plus. 

```
    conversion_techno:
        name: 'Test conversion and conversion_plus'
        parent: conversion #conversion_plus
        export: true
        carrier_in: gas
        carrier_out: 
            heat
        #carrier_out_2:
            #power: 1
        constraints:
            e_cap.max: 1300
        costs:
            monetary:
                om_var: -100.001
```
I used a om_var for the supply of gas of 1 and a constant demand of -1 for heat and power

It appears that the conversion technology will work at full capacity and produce an excess of heat (because of the negative O&M cost). But on the contrary, the conversion_plus technology will not produce more than the demand, even if it would be more economically interesting to produce at full capacity.

I guess it is because the export option isn't working for one of the 2 carriers in conversion_plus.

Conversion
![conversion](https://user-images.githubusercontent.com/29625919/28172952-5074e4cc-67ed-11e7-8170-467c14baa4cc.png)

Conversion_plus
![conversion_plus](https://user-images.githubusercontent.com/29625919/28172962-58413502-67ed-11e7-9d25-b3d47e58bd04.png)
