### ISSUE TITLE
Add `title` or `long-name` parameter to math syntax

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#582]
### What can be improved?

This would add a longer name to math components that can be extracted and used in downstream visualisation. E.g.,

```yaml
variables:
  flow_cap:
    title: Flow capacity
    description: >-
      A technology's flow capacity, also known as its nominal or nameplate capacity.
    default: 0
    unit: power
    foreach: [nodes, techs, carriers]
    bounds:
      min: flow_cap_min
      max: flow_cap_max

```

### Version

v0.7.0.dev
