### ISSUE TITLE
Specify "ordered sets" to simplify synthax

### ISSUE THREAD

**Issue by irm-codebase** [calliope-project/calliope#605]
### What can be improved?

Calliope makes use of `roll()` and `get_val_at_index()` in cases were the position of a set matters. This is often used for clustering and storage balancing constraints.

Although this works, I think the approach has two weaknesses:
- For sets defined by names, like `nodes` and `techs`, using these functions would not make sense. We currently do not protect against it.
- It's very wordy, and sort of contradicts the "simple to read" approach of Calliope

### Proposed improvement

Some optimization libraries, like `pyomo`, allow you to specify "ordered sets". I think this makes a lot of sense in our case, and would enable easier syntax and checks.

We currently do not define the dimensions directly, but I think something like this would be good:

```yaml
dimensions:
  nodes:
  techs:
  carriers:
  timesteps:
    ordered: true
  investsteps:
    ordered: true
```

**Syntax:** allowed ONLY for ordered dimensions
- 0: first position
- -1: last position
- << n: roll / shift n backwards
- \>\> n: roll / shift n forward

Then, a constraint like

```yaml
link_storage_level:
  description: Link the storage level at the end of one investment step to the start of the next.
  foreach: [nodes, techs, investsteps]
  where: storage AND NOT investsteps=get_val_at_index(investsteps=0)
  equations:
    - expression: >-
        storage[timesteps=$initial_step] == roll(
          storage[timesteps=$final_step] * (
            (1 - storage_loss) ** timestep_resolution[timesteps=$final_step]
          ),
          investsteps=1
        )
  slices:
    initial_step:
      - expression: get_val_at_index(timesteps=0)
    final_step:
      - expression: get_val_at_index(timesteps=-1)
```

May turn to:

```yaml
link_storage_level:
  description: Link storage level... but easier this time!
  foreach: [nodes, techs, investsteps]
  where: storage AND NOT investsteps == investsteps[0]
  equations:
  - expressions: >-
      storage[timesteps[0]] == storage[timesteps[-1], investsteps<<1] * (
        (1-  storage_loss)**timestep_resolution[timesteps[-1]]
      )
```

or (my least favourite)

```yaml
link_storage_level:
  description: Link storage level... but easier this time!
  foreach: [nodes, techs, investsteps]
  where: storage AND NOT investsteps[0]
  equations:
    - expression: >-
        storage[timesteps=$initial_step] == storage[timesteps=$final_step, investsteps<<1] * (
            (1 - storage_loss) ** timestep_resolution[timesteps=$final_step]
          )
  slices:
    initial_step:
      - expression: timesteps[0]
    final_step:
      - expression: timesteps[-1]
```

### Version

v0.6.10
