### ISSUE TITLE
Overriding supply.constraints.r

### ISSUE THREAD

**Issue by arnaud-leroy** [calliope-project/calliope#61]
Hello,
I try to override different parameters in the locations.yaml file and it is working fine except for the r constraint of supply technologies.

For example, overriding the r parameter of photovoltaic technology. Here are my locations.yaml and techs.yaml files:

```

###
# LOCATIONS
###
locations:
  Loc_South_tyrol_2014:
    available_area: 100000000.0
    override:
      demand_power.constraints.r: file
      photovoltaic.constraints.r: file 

    techs:
    - demand_power
    - unmet_demand_power
    - photovoltaic
    - supply_power
```
```

###
# TECHNOLOGY
###
techs:
  demand_power:
    carrier: power
    name: Power demand
    parent: demand

  photovoltaic:
    name: 'Solar photovoltaic power'
    parent: supply
    carrier_out: power
    constraints:
      #r: file
      e_eff: 0.85
      e_cap.max: inf
      r_area.max: 7000
    costs:
      monetary:
        e_cap: 5

  supply_power:
    carrier: power
    constraints:
      e_cap.max: .inf
    costs:
      monetary:
        om_fuel: 100.0
    name: Electrical Grid
    parent: supply

  unmet_demand_power:
    carrier: power
    name: Unmet power demand
    parent: unmet_demand

```

The results is :
![image](https://user-images.githubusercontent.com/29625919/28911856-3351d7f6-7832-11e7-93dc-ae266ce1a0ca.png)
Gurobi isn't happy and it is the same with glpk.

But if I comment     `  photovoltaic.constraints.r: file ` in locations.yaml and uncomment `#r: file` in techs.yaml, the optimization runs fine.

If I understand it well, both option with r defined in locations.yaml and techs.yaml should give the same results.
The strange part is that overriding the demand_power.constraints.r in locations.yaml is not causing any trouble.

Thanks for your help! 😀

**Comment by brynpickering** [comment]
Can you post the first two rows of demand_power_r.yaml and photovoltaic_r.yaml?

**Comment by arnaud-leroy** [comment]
Yes, here they are:

demand_power_r.csv

  | Loc_South_tyrol_2014
-- | --
0 | -205.932
1 | -198.071



photovoltaic_r.csv

  | Loc_South_tyrol_2014
-- | --
0 | 0
1 | 0

**Comment by brynpickering** [comment]
Thanks Arnaud. I can't seem to be able to replicate your problem, it works fine for me defining a location override for `r`, for any relevant technology type. The error comes from constraint generation, there is a strange constraint being generated. Are you able to work out what constraint `inf*x1 + 1.176..*x115 - 0.49...` might refer to?

**Comment by arnaud-leroy** [comment]
Sorry, you are true, the error is not appearing with the simplified example I sent ...

In fact in my original model, I had 2 locations but the second location has nothing to do with photovoltaic technology. So I skipped that location to explain the model... Wrong decision!

Here are my new files, with 2 locations. With the first location commented, it is working fine, but if you uncomment it, the error will appears

techs.yaml

```
###
# TECHNOLOGY
###
techs:
  demand_power:
    carrier: power
    name: Power demand
    parent: demand

  photovoltaic:
    carrier_out: power
    constraints:
      #r: file
      e_cap.max: .inf
      force_r: true
      r_area.max: inf
    costs:
      monetary:
        e_cap: 5.0
        om_fixed: 0.0
    depreciation:
      plant_life: 25.0
    name: Photovoltaic Panels
    parent: supply
                



  supply_power:
    carrier: power
    constraints:
      e_cap.max: .inf
    costs:
      monetary:
        om_fuel: 10000.0
    name: Electrical Grid
    parent: supply
    
  unmet_demand_power:
    carrier: power
    name: Unmet power demand
    parent: unmet_demand
```

locations.yaml files with only one location: it is working!
```
###
# LOCATIONS
###
locations:

  # Loc_Grid_elec_gas:
    # available_area: 100.0
    # override:
      # demand_power.constraints.r: file
    # techs:
    # - supply_power
    # - demand_power
    # - unmet_demand_power
    
  Loc_South_tyrol_2014:
    available_area: 100000000.0
    override:
      demand_power.constraints.r: file #=South_Tyrol_Elec_demand_based on NORD_Italy_2014.csv
      photovoltaic.constraints.e_cap.equals: 500.0
      photovoltaic.constraints.r: file 
    techs:
    - supply_power
    - demand_power
    - unmet_demand_power
    - photovoltaic

```


Thanks!
