### ISSUE TITLE
Overriding depreciation values isn't working

### ISSUE THREAD

**Issue by arnaud-leroy** [calliope-project/calliope#64]
Hello,

I try to overwrite the plant_life and monetary.interest for a technology but it isn't changing the cost-result for that technology.

locations.yaml:
```
locations:
    L1:
        techs: [
         'supply_power',
         'demand_power',
         'unmet_demand_power'
         ]
        override:
            demand_power.constraints.r: -10
            supply_power.depreciation.plant_life: 4
            supply_power.depreciation.interest.monetary: 0.5
```
techs.yaml:
```
techs:
    supply_power:
        name: 'Electricity import'
        parent: supply
        carrier: power
        constraints:
            r: inf
            e_cap.max: inf
        costs:
            monetary:
                e_cap: 10
                om_fuel: 1 # €/MWh electricity price
        depreciation:
            plant_life: 20  # Lifetime of a plant (years)

    demand_power:
        name: 'Electrical demand'
        parent: demand
        carrier: power

    unmet_demand_power:
        name: 'Unmet electrical demand'
        parent: unmet_demand
        carrier: power
```
