### ISSUE TITLE
Data sources and templates

### ISSUE THREAD

**Issue by irm-codebase** [calliope-project/calliope#676]
### What can be improved?

I am not entirely sure if this is possible in the new math, so I'm filing this as a _potential_ feature request.
Otherwise, it might be a documentation oversight...

------------------------

In v0.6.10 it used to be possible to set data sources for `tech_groups` (now `templates`):

```yaml
tech_groups:
    wind_onshore:  # from [@JRC:2014] Table 4
        essentials:
            name: Onshore wind
            carrier: electricity
            parent: supply
        constraints:
            resource: file=supply/capacityfactors-wind-onshore.csv
            resource_unit: energy_per_cap
            lifetime: 25
```

Since data sources are now a separate section, I assume this is no longer possible, since you need to provide dimensions to them (which `templates` do not have, since the `tech` is set later).

Is there a way to support this?
People can define this for each tech, but it diminishes the usefulness of templates a bit.

### Version

v0.7.0.dev3
