### ISSUE TITLE
Ambiguous tabular data reads

### ISSUE THREAD

**Issue by irm-codebase** [calliope-project/calliope#678]
### What happened?

The current implementation of tabular data reading is a bit finicky: sometimes it cares about the name of a row/column, sometimes it does not.

For example, picture this relatively common timeseries setup:

```yaml
data_sources:
  roof_mounted_pv_timeseries:
    source: timeseries/supply/capacityfactors-rooftop-pv.csv
    columns: nodes
    rows: timesteps
    add_dims:
      techs: roof_mounted_pv
      parameters: source_use_max
```

This command will pass for the following file setups:

![image](https://github.com/user-attachments/assets/5da49f6d-e4e9-464c-90af-58c0b0b10c79)
![image](https://github.com/user-attachments/assets/62a29754-f691-4288-b43a-b7fd264d7e99)

But it will fail for this one:
![image](https://github.com/user-attachments/assets/06465a75-6898-43d9-803a-73201f7dd271)

This is a bit confusing from a user perspective: why does the program suddenly care about the name of the column, if it is able to infer it from the `yaml` configuration?

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Version

v0.7.0.dev3
