### ISSUE TITLE
Building support for monthly charges into Calliope

### ISSUE THREAD

**Issue by jmorrisnrel** [calliope-project/calliope#727]
### What can be improved?

Idea/Goal:
Define custom lookup arrays on specific indices to enable more advanced constraint/expression `where` filtering.

Background:
We have been running into models/scenarios where we want to have technologies in Calliope that have monthly bills including monthly peak energy usage charges. Examples could include certain third-party power purchase agreements or even utility tariffs and the monthly power bills that a customer sees. We have modeled this in Calliope using multiple capacity expansion transmission/conversion techs/nodes, having one enabled (via efficiency) each month which is a pretty clunky workaround.

We have been looking into the custom math options in 0.7 to see if we can simplify building this behavior/make it more efficient and have been considering adding new expressions or decision variables to track the peak demand each month so we can apply costs to it. We're struggling to work out a way to tie values on the `timesteps` index to months in the expression `where` clauses. `select_from_lookup_arrays` looks like it would be the right helper function if we could get a lookup array with the month for each timestep, but we don't see a way to add a lookup array to the problem formulation.

If there is a way to add a lookup array to the problem formulation, we could potentially selectively enable constraints based on month, weekday/weekend, or any other categorization of timesteps/index values. A work around could be to define a timeseries parameter at the tech (or a master template) level with the month of each timestep that we can then access in a `where` clause.

Adding more decision variables might not even improve the performance of the model compared to multiple techs, but wanted to flag a potential use for the ability to add custom lookup arrays or find another way to categorize index values to enable more flexible constraint definition.

### Version

v0.7.0dev4

**Comment by brynpickering** [comment]
This is a common use-case and could be dealt with in a variety of ways right now. The one I'd recommend is to create your lookup table in a CSV as:

```
timesteps            months    lookup_month
2005-01-01 00:00:00  1        1.0
2005-01-01 01:00:00  1        1.0
                             ... 
2005-12-31 22:00:00  12       1.0
2005-12-31 23:00:00  12       1.0
```

Then load it in as a data table

```yaml
data_tables:
  lookup_month:
    data: <path/to/file.csv>
    rows: [timesteps, months]
    columns: parameters
```

And then use it in custom math:

```yaml
global_expressions:
  monthly_cost:
    foreach: ["techs", "nodes", "months", "costs", "carriers"]
    where: "flow_out"
    equations:
      - expression: sum(where(flow_out, lookup_month), over=timesteps) * cost_month
 
constraints:
  max_monthly:
    foreach: ["techs", "nodes", "months", "costs", "carriers"]
    where: "flow_out"
    equations:
      - expression: sum(where(flow_out, lookup_month), over=timesteps) <= flow_out_monthly_max
```

where `cost_month` and `flow_out_monthly_max` are parameters you've defined indexed over the `months` dimension + techs/nodes/carriers etc.

**Comment by jmorrisnrel** [comment]
I've been doing some testing to try and get a specific variation of monthly costs working and have been having some issues getting the new cost expression included in the global `cost` expression.

The cost is supposed to be a monthly cost based on the "peak" usage of the technology. I've introduced a new decision variable indexed over a new months dimension and constrained it to match the peak `flow_out` each month. I've also added an expression to calculate the resulting monthly cost.

```
variables:
  flow_peak_month:
    title: Monthly Peak Flow Out
    description: >-
      The peak flow out for each month. Useful for applying a monthly peak use cost (i.e. utility rate demand charges).
    default: 0
    unit: power
    foreach: [nodes, techs, carriers, months]
    where: monthly_peak_mode
    bounds:
      min: 0
      max: .inf

constraints: 
  flow_max_jan:
    description: >-
      Constrain monthly flow max to be no more than flow_cap.
    foreach: [nodes, techs, carriers, months]
    equations:
      - where: monthly_peak_mode
        expression: flow_peak_month <= flow_cap
  
  flow_min_jan:
    description: >-
      Constrain monthly flow min to be no less than flow_out.
    foreach: [timesteps, months, nodes, techs, carriers]
    equations:
      - where: monthly_peak_mode
        expression:  flow_out <= flow_peak_month

global_expressions:
  cost_peak_charge_month:
    title: Monthly Peak Flow Charge
    description: >-
      The costs associated with the monthly peak flow_out of a technology.
    default: 0
    unit: cost_per_month
    foreach: [nodes, techs, costs, months, carriers]
    where: monthly_peak_mode AND cost_peak_month
    equations:
      - expression: cost_peak_month * flow_peak_month
```

The variable, constraints, and expression are all working, but when I try and add the `cost_peak_charge_month` into the main `cost` expression matching the logic/syntax for `cost_operation_variable` I encounter a couple issues.

```
cost:
  title: Total costs
  description: >-
    The total annualised costs of a technology,
    including installation and operation costs.
  default: 0
  unit: cost
  foreach: [nodes, techs, costs]
  where: "cost_investment_annualised OR cost_operation_variable OR cost_operation_fixed OR cost_peak_charge_month"
  equations:
    - expression: >-
        default_if_empty(cost_investment_annualised, 0) +
        $cost_operation_sum + $cost_peaks_sum +
        default_if_empty(cost_operation_fixed, 0)
  sub_expressions:
    cost_operation_sum:
      - where: "cost_operation_variable"
        expression: sum(cost_operation_variable, over=timesteps)
      - where: "NOT cost_operation_variable"
        expression: "0"
    cost_peaks_sum:
      - where: "cost_peak_charge_month"
        expression: sum(cost_peak_charge_month, over=[carriers, months])
      - where: "NOT cost_peak_charge_month"
        expression: "0"
```
The first issue is the where clauses for `cost_peaks_sum` which don't seem to register that `cost_peak_charge_month` is set for my test techs. I can work around this by adjusting the where to check for the control parameter (`monthly_peak_mode`) instead of the expression, but it seems like it should work with `cost_peak_charge_month` like the operation cost expression does above it.

Once I adjust the where clause so it triggers on my test technology, I encounter a different issue where `sum(cost_peak_charge_month, over=[carriers, months])` doesn't seem to resolve and I get a `TypeError: unsupported operand type(s) for +: 'SumExpression' and 'str'`. I'm mirroring the logic used for `cost_operation_variable` so I'd expect this constraint to work unless summing over dimensions other than timesteps is causing an issue.

I've tried a couple of different formulations to see if I can identify what's causing the issues including adjusting `cost_peak_charge_month` to be set for all carriers/months and adjusting it to split the carrier and month sums between the two expressions, but haven't had any success.

I've attached the full model as well as the CSV dump of the results. 

[meter_testing.zip](https://github.com/user-attachments/files/19351258/meter_testing.zip)
