### ISSUE TITLE
Memory error due to huge array introduced by `default_if_empty` in custom math

### ISSUE THREAD

**Issue by jnnr** [calliope-project/calliope#735]
### What happened?

I am using custom math to define group constraints on groups of links. I am using the helper function `default_if_empty` as an indicator functions. When scaling up an toy example to a larger scale, I get the following error:

```
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 775. GiB for an array with shape (98, 191, 1, 2920, 34, 56) and data type object
```
Indeed, 98 nodes * 191 links * 1 carriers * 2920 timesteps * 34 node_groups * 56 link_groups create an array with ~100*1e9 elements.
However, this array is in reality very sparse - most of them are zero. The actual number of constraints is only 56 link_groups * 2 (upper and lower bound) * 2920 timesteps.

This is the custom math I am adding

```
constraints:
  constraint_link_flow_out_group_ub:
    foreach: [node_groups,link_groups,carriers,timesteps]
    where: "base_tech=transmission AND carriers=electricity AND flow_out_link_group"
    equations:
      - expression: sum(flow_out * default_if_empty(lookup_link_group, 0) * default_if_empty(lookup_node_group, 0), over=[techs,nodes]) <= flow_out_link_group
```

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [x] Linux

### Version

v0.7.0.dev4

### Relevant log output

```Shell

```

**Comment by brynpickering** [comment]
So, I expect this to be a constant issue without summing over groups as the first step. Could you try the following with your model @jnnr:

1. create a new helper function that will apply a grouped summation:
```python
import pandas as pd
import xarray as xr
from calliope.backend.helper_functions import ParsingHelperFunction


class GroupbySum(ParsingHelperFunction):
    # Class name doesn't match NAME to avoid a clash with typing.Any
    #:
    NAME = "groupby_sum"
    #:
    ALLOWED_IN = ["where", "expression"]

    ignore_where = True

    def as_math_string(self, array: str, over: str, group: str) -> str:  # noqa: D102, override
        overstring = self._instr(over)
        foreach_string = rf"{overstring} \text{{ if }} \text{{{group}}}(\text{{{over.removesuffix('s')}}}) = \text{{{group[0]}}}"
        overstring = rf"\substack{{{foreach_string}}}"

        return rf"\sum\limits_{{{overstring}}} ({array})"

    def as_array(
        self, array: xr.DataArray, grouper: xr.DataArray, group_dim: str
    ) -> xr.DataArray:
        """Sum an array over the given grouper.

        Args:
            array (xr.DataArray): expression array
            grouper (xr.DataArray): Array with which to group the array.
            group_dim (str): Name of dimension that the grouper values are members of.
                This will become a new dimension over which the array is indexed once grouping is complete.


        Returns:
            xr.DataArray:
                Array with dimension(s) aggregated over the grouper.

        """
        # We can't apply typical xarray rolling window functionality
        grouped: dict[str | int, xr.DataArray] = {}

        grouper = self._input_data[grouper.name]

        grouping_dims = grouper.dims
        groups = array.stack(_stacked=grouping_dims).groupby(
            grouper.stack(_stacked=grouping_dims)
        )
        for group_name, array_subset in groups:
            grouped[group_name] = array_subset.sum("_stacked", min_count=1, skipna=True)

        array = xr.concat(
            grouped.values(), dim=pd.Index(grouped.keys(), name=group_dim)
        )
        return array
```

2. update your group definition to a multi-dimensional array (i.e., over nodes and techs), e.g.:
```yaml
parameters:
  group_links_and_nodes:
    data: [A1, A2, B1, B2, B1, B2]
    index: [
      [link_X1_X2, X1],
      [link_X1_X2, X2],
      [link_X2_X3, X2],
      [link_X2_X3, X3],
      [link_X3_X1, X1],
      [link_X3_X1, X3]
    ]
    dims: [techs, nodes]
  node_link_limits:
    data: [1, 2, 3, 4]
    index: [A1, A2, B1, B2]
    dims: [link_node_groups]
```
It would likely be easiest to define those groupings in a data table

3. update your math definition to utilise the new helper function:
```yaml
constraints:
  set_link_limits:
    foreach: [link_node_groups, timesteps]
    where: node_link_limits
    equations:
      - expression: groupby_sum(flow_out[carriers=electricity], group_links_and_nodes, link_node_groups) <= node_link_limits
```

4. Put it all together by loading in the helper function file before you build the model (or having the helper function class defined in the same script as you load the model):
```python
import calliope
import my_new_helper_func

m = calliope.Model(...)
m.build()
m.solve()
```

My concern is that array stacking (necessary for multidimensional grouping) will be slow/memory intensive. I don't have anything to base that assumption on right now as the models I'm using to test are quite small so differences are often marginal and could be noise. If you can see what effect it has in your situation, that would be great.
