### ISSUE TITLE
Moving to `pydantic`: isolate dimension-related data (i.e., `techs`, `nodes`).

### ISSUE THREAD

**Issue by irm-codebase** [calliope-project/calliope#738]
### What can be improved?

'Mutable' dimensional data should be isolated under its own key in the schema.

```yaml
config:  # structural, contains stuff that affects code behaviour
math: # structural, contains stuff that affects backend mathematics
data: # structural, contains data definition in YAML
    techs: # data for a dimension
    nodes: # data for a dimension
    vintages:  # data for a future 'vintages' dimension
data_tables: # structural, contains stuff that defines extraction from files
```

This would allow use to add / remove dimension functionalities without impacting other portions of the configuration files.

See #726 for more information

### Version

v0.7
