### ISSUE TITLE
Resource profile is not following the input

### ISSUE THREAD

**Issue by arnaud-leroy** [calliope-project/calliope#76]
Maybe it is related to issue #75.

I developed a simple model with hydropower, a battery and a power demand. The hydropower profile, which is defined in a file with the r parameter, do not follow the profile. The profile is defined with a constant value for each month. 
Instead of that, the hydropower is taking for the nth day of each month the value of the nth-month  (first day has the value of january, 2nd day of February... 12th day of december) and it comes back to the normal value at the 13th day. 
I tested it with the different versions of calliope installed on my computer and all have shown the same issue. I tried to modified the hydropower profile and the file defining the time but the same problem persisted.

To display the problem more clearly, these are pictures of the results, over the 5 first months and over the 5 first days.
![ror not working](https://user-images.githubusercontent.com/29625919/32105234-1010ad38-bb28-11e7-9266-838fdcaa1336.png)
![ror not working-2](https://user-images.githubusercontent.com/29625919/32105237-11cf6d3a-bb28-11e7-8147-f6625394f731.png)

Thanks for your help, extract of the  files are presented below
Arnaud

this is the techs file:
```
techs:
  demand_power:
    carrier: power
    name: Power demand
    parent: demand
  large_battery:
    carrier: power
    color: '#f0ff00'
    constraints:
      e_cap.max: .inf
      s_cap.max: .inf
    costs:
      monetary:
        e_cap: 1.0
        om_var: 1.0
        s_cap: 350000.0
    name: Large battery
    parent: storage
  ror_Hydro:
    carrier: power
    color: '#1637df'
    constraints:
      e_cap.max: .inf
      force_r: true
      r: file=ror_south_tyrol.csv
    costs:
      monetary:
        e_cap: 3300000.0
        om_frac: 1.1
    name: Run of River Hydro
    parent: supply
  unmet_demand_power:
    carrier: power
    name: Unmet power demand
    parent: unmet_demand
```

and this is an extract of the ror_south_tyrol.csv:

```
  | South_tyrol
-- | --
0 | 360.7258
1 | 360.7258
...
23 | 360.7258
24 | 360.7258
...
47 | 360.7258
48 | 360.7258
...
71 | 360.7258
72 | 360.7258
...
95 | 360.7258
96 | 360.7258
```
